### ISSUE TITLE
pyload: 0.5.0b3.dev72 -> 0.5.0b3.dev74

### ISSUE THREAD

**Issue by milahu** [milahu/nur-packages#2]
@ruby0b please update

https://github.com/milahu/nur-packages/commit/4c901004d59c38b9c859477d7ed1fad9cfbc759f

https://github.com/NixOS/nixpkgs/pull/242260

[pyload-ng.nix in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/pyload-ng/default.nix)

[pyload in milahu/nur-packages](https://github.com/milahu/nur-packages/blob/master/pkgs/python3/pkgs/pyload/pyload.nix)

> not sure what Flask-Session2 is but flask-session works just fine

[flask-session2.nix](https://github.com/milahu/nur-packages/blob/master/pkgs/python3/pkgs/flask-session2/flask-session2.nix)

**Comment by ruby0b** [comment]
looked into it and there's a good reason you're banned.
please change and grow as a person.

blocked

**Comment by milahu** [comment]
haha, emos gonna cry... shut up and do your job as a "package maintainer"

**Comment by milahu** [comment]
6523a1f4052fa7db29126787c323b8cb1db8cefc
